M48
; DRILL file KiCad 10.0.4 date 2026-08-13T17:06:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-13T17:06:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.600
%
G90
G05
T1
X46.551Y-148.901
X100.765Y-74.93
X148.0Y-112.0
X148.631Y-28.15
X251.14Y-148.83
T2
X249.682Y-106.611
T3
X46.617Y-68.02
X250.579Y-68.02
M30
